#!/usr/bin/perl -w

#
# NethServer Mail Server events configuration
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);
use File::Path;

#
# nethserver-kopano-webapp-update event
#
# templates
event_templates('nethserver-kopano-webapp-update', qw(
    /etc/httpd/conf.d/default-virtualhost.inc
    /etc/httpd/conf.d/kopano-webapp.conf
));
# actions/services:
event_actions('nethserver-kopano-webapp-update', qw(
    initialize-default-databases 00
));
event_services('nethserver-kopano-webapp-update', qw(
    httpd reload
));

#
# trusted-networks-modify event
#
# templates
event_templates('trusted-networks-modify', qw(
    /etc/httpd/conf.d/kopano-webapp.conf    
));
# actions/services:
#event_actions('trusted-networks-modify', qw(
#));
event_services('trusted-networks-modify', qw(
    httpd reload
));
